server:
  port: ${APP_PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true

logging:
  level:
    org.springframework.jdbc: DEBUG
