server:
  port: ${APP_PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
  data:
    web:
      pageable:
        one-indexed-parameters: true

jwt:
  base64-secret: 2ZfCLkmZQa8jh294Db6W4lS1InE5E7Lcyo3QtJQmmvM/j0+V5/stHDXi+OuboWOiAQprw5GxF29WCQfw2DKXGA==
  expiration:
    access-token: 18000
    refresh-token: 2592000

logging:
  level:
    org.springframework.jdbc: DEBUG
